[package]
name = "matriarch-settings"
version = "0.1.0"
edition = "2021"
authors = ["Jeremy March <jmarch@gradcenter.cuny.edu>"]

[dependencies]
gtk = { version = "0.6.4", package = "gtk4" }
adw = { version = "0.3.1", package = "libadwaita" }
midir = "0.9.1"
