[package]
name = "matriarch-settings"
version = "0.1.0"
edition = "2021"
authors = ["Jeremy March <jmarch@gradcenter.cuny.edu>"]

[dependencies]
gtk = { version = "0.4.7", package = "gtk4" }
adw = { version = "0.1.1", package = "libadwaita" }
midir = "0.7.0"
