[package]
name = "matriarch-settings"
version = "0.1.0"
edition = "2021"
authors = ["Jeremy March <jmarch@gradcenter.cuny.edu>"]

[dependencies]
gtk = { version = "0.9.3", package = "gtk4", features = ["v4_16"] }
adw = { version = "0.7.1", package = "libadwaita" }
midir = "0.9.1"
